version: "3"

services:

  # akafuyu-backend:
  #   container_name: project-akafuyu-backend
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   environment:
      # PORT: 7700
  #   ports:
  #     - "7700:7700"
  #   networks:
  #     - default
  #   depends_on:
  #     - mysql

  mysql:
    image: mysql
    container_name: project-akafuyu-db
    environment:
      MYSQL_ROOT_PASSWORD: 4321
      MYSQL_DATABASE: akafuyu
    networks:
      - default
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: project-akafuyu-pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - default
    ports:
      - 8081:80

volumes:
  data:
